apiVersion: v1
kind: Service
metadata:
  labels:
    app: golang-app
  name: golang-app-service
  namespace: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: golang-app
  type: LoadBalancer
