apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: app
data:
  prometheus.rules: |-
#    groups:
#      rules:
  prometheus.yml: |-
    global:
      scrape_interval: 60s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules

    scrape_configs:
    - job_name: 'golang'

      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

      static_configs:
        - targets: ['golang-app-service']
