apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: app
data:
  prometheus.rules: |-
    groups:
    - name: golang
      rules:
      - record: responseAvg
        expr: avg without (path) ( rate(go_app_response_latency_seconds_sum[5m])) / avg without (path) ( rate(go_app_response_latency_seconds_count[5m]))
      - alert: responseTooLate
        expr: responseAvg > 1

  prometheus.yml: |-
    global:
      scrape_interval: 60s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules

    scrape_configs:
    - job_name: 'golang'

      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

      static_configs:
        - targets: ['golang-app-service']
