apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-server-service
  name: prometheus-server-service
  namespace: app
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-server
  type: LoadBalancer
